project:
  type: website
  output-dir: docs
  
website:
  title: "Sportvid"
  favicon: favicon.ico
  navbar:
    left:
      - href: about.qmd
        text: "Über das Projekt"
      - href: team.qmd
        text: "Projektteam"
      

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    toc-title: "Auf dieser Seite"

editor: visual

